### ISSUE TITLE
🐛 bug([context]): Bump from alpha to beta

### ISSUE THREAD

**Issue by antoinenedelecdecathlon** [Resnovas/smartcloud#566]
## Describe the bug

```
  Error: Error thrown while processing config: HttpError: No commit found for the ref refs/pull/3494/merge
  Error: undefined did not complete due to error:[object Promise]
```

### To Reproduce

Our `.github/workflow/label.yaml`:
```
on:
    pull_request:
        types: [ opened, reopened, edited, synchronize, converted_to_draft ]
        branches:
          - '**'        # matches every branch
          - '!master'   # excludes master

name: 'Labeler'
jobs:
    label:
        runs-on: xxx
        steps:
            -   uses: actions/checkout@v4
            -   uses: Resnovas/smartcloud@1.0.0-beta.8
                with:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

```

### Expected behaviour

Once we started to pass from `1.0.0-alpha.7` on the `1.0.0-beta.X` branches, this error occurs:

```
  Error: Error thrown while processing config: HttpError: No commit found for the ref refs/pull/3494/merge
  Error: undefined did not complete due to error:[object Promise]
```
